---
helper:
  config: &config
    filename: ""
    dump: ""
  prog: &prog
    input:
      type: list
      value:
      -
      nargs: "*"
    output: ""
  logging: &logging
    verbosity:
      type: str
      value: INFO
      choices:
      - DEBUG
      - INFO
      - WARN
      - ERROR
      - CRITICAL
  ctc_beam_search_decoder: &ctc_beam_search_decoder
    top_paths: 3
  bucket: &bucket
    step_size: 4
    minimum_size: 32
    count: 400
    capacity: 32
    num_threads: 1
  input: &input
    batch_size: 30
    num_epochs: 100
    buffer_size: 1000
  learning: &learning
    rate:
      type: float
      value: 1e-5
    decay_rate:
      type: float
      value: 0.8
    decay_steps:
      type: int
      value: 100
  image: &image
    shape: # (height, width, depth)
    -
    -
    - 3
  initializer: &initializer
    vgg16:
      type: dict
  regularizer: &regularizer
    scale: 0.0005
  non_max_suppression: &non_max_suppression
    max_output_size: 20000
    iou_threshold: 0.5
  model: &model
    name:
      type: str
    model:
      type: module
    directory:
      type: str
    process: # ["train", "evaluate", "predict"]
      value:
      - train
      type: list
      nargs: "*"
      choices:
      - train
      - evaluate
      - predict
    config:
      type: module
  dataset: &dataset
    train:
      value:
      - "*trainset.tfrecord"
      type: list
      action: "append"
    test:
      value:
      - "*teseset.tfrecord"
      type: list
      action: "append"
    validation:
      value:
      - "*validationset.tfrecord"
      type: list
      action: "append"
    label: "label.txt"
