---
schema:
  config: &config
    file: ""
    dump: ""
  prog: &prog
    input:
      .type: list
      value:
      -
      argparse:
        nargs: "*"
    output: ""
  logging: &logging
    verbosity:
      .type: str
      value: INFO
      argparse:
        choices:
        - DEBUG
        - INFO
        - WARN
        - ERROR
        - CRITICAL
